"use client";

type Component = {
  id: string;
  name: string;
  vendor?: string;
  description: string;
  evidence?: string;
  console_url?: string;
};

type Category = {
  key: string;
  label: string;
  components: Component[];
};

export type ExportableBlueprint = {
  summary?: string;
  categories?: Category[];
  connections?: Array<{ from: string; to: string; label?: string }>;
  decisions?: Array<{
    title: string;
    category: string;
    risk: string;
    rationale: string;
    evidence?: string;
  }>;
  risks?: Array<{
    title: string;
    severity: string;
    description: string;
    remediation?: string;
  }>;
};

export function ExportButtons({
  blueprint,
  projectName,
}: {
  blueprint: ExportableBlueprint;
  projectName: string;
}) {
  function downloadJson() {
    const blob = new Blob([JSON.stringify(blueprint, null, 2)], {
      type: "application/json",
    });
    triggerDownload(blob, slugify(projectName) + "-blueprint.json");
  }

  function downloadMarkdown() {
    const blob = new Blob([toMarkdown(blueprint, projectName)], {
      type: "text/markdown",
    });
    triggerDownload(blob, slugify(projectName) + "-blueprint.md");
  }

  return (
    <div className="export-buttons">
      <button
        type="button"
        onClick={downloadMarkdown}
        className="status-secondary-btn"
      >
        Download as Markdown
      </button>
      <button
        type="button"
        onClick={downloadJson}
        className="status-secondary-btn"
      >
        Download as JSON
      </button>
    </div>
  );
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "blueprint";
}

function toMarkdown(bp: ExportableBlueprint, projectName: string): string {
  const lines: string[] = [];
  lines.push(`# Blueprint — ${projectName}`);
  lines.push("");
  lines.push(`*Generated by StackLense*`);
  lines.push("");
  if (bp.summary) {
    lines.push("## Summary");
    lines.push("");
    lines.push(bp.summary);
    lines.push("");
  }

  if (bp.categories && bp.categories.length > 0) {
    for (const cat of bp.categories) {
      lines.push(`## ${cat.label}`);
      lines.push("");
      if (!cat.components || cat.components.length === 0) {
        lines.push("_Not detected._");
        lines.push("");
        continue;
      }
      for (const c of cat.components) {
        const heading = c.console_url
          ? `### [${c.name}](${c.console_url})`
          : `### ${c.name}`;
        lines.push(heading);
        if (c.vendor && c.vendor !== c.name) {
          lines.push(`**Vendor:** ${c.vendor}`);
        }
        lines.push("");
        lines.push(c.description);
        lines.push("");
        if (c.evidence) {
          lines.push(`_Detected: ${c.evidence}_`);
          lines.push("");
        }
      }
    }
  }

  if (bp.connections && bp.connections.length > 0) {
    lines.push("## Connections");
    lines.push("");
    for (const conn of bp.connections) {
      const lbl = conn.label ? ` (${conn.label})` : "";
      lines.push(`- \`${conn.from}\` → \`${conn.to}\`${lbl}`);
    }
    lines.push("");
  }

  if (bp.decisions && bp.decisions.length > 0) {
    lines.push("## Decisions");
    lines.push("");
    for (const d of bp.decisions) {
      lines.push(`### ${d.title}`);
      lines.push(`**Risk:** ${d.risk} · **Category:** ${d.category}`);
      lines.push("");
      lines.push(d.rationale);
      lines.push("");
      if (d.evidence) {
        lines.push(`_Evidence: ${d.evidence}_`);
        lines.push("");
      }
    }
  }

  if (bp.risks && bp.risks.length > 0) {
    lines.push("## Risks");
    lines.push("");
    for (const r of bp.risks) {
      lines.push(`### ${r.title}`);
      lines.push(`**Severity:** ${r.severity}`);
      lines.push("");
      lines.push(r.description);
      lines.push("");
      if (r.remediation) {
        lines.push(`**Fix:** ${r.remediation}`);
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}
